# COOONTAINER — campaign wave 2 (appended orders only).
# hangar_09..14, storage_13..22, garages_09..18, port_07..14.
# Existing 01.. lots stay untouched; PREVIEW_FILL only writes empty TALE/DOCS.

from __future__ import annotations


def build_more(S, stack_y, brick_stack, box_wall_front) -> list:
    def cups(x0, z0, nx, nz, item="cup_okayest", dx=0.22, dz=0.22, y=0.0):
        out = []
        for ix in range(nx):
            for iz in range(nz):
                out.append(S(item, x0 + ix * dx, y, z0 + iz * dz, (ix - iz) * 7))
        return out

    def books(x, z, ids, dy=0.05):
        return [S(iid, x, i * dy, z, 72 + i * 4) for i, iid in enumerate(ids)]

    lots: list[dict] = []

    # =====================================================================
    # HANGAR 09–14   continue L B J L L L B L | L J B L J L
    # BAG 1.5³  min_bid 8–40  lock ~0.05  preview 12–18  clearout 60–85
    # =====================================================================

    lots.append({
        "id": "hangar_09", "district": "HANGAR", "kind": "BAG", "order": 9,
        "min_bid": 14, "info": "DOOR15", "pacing": "LEAN",
        "preview": 14, "clearout": 72, "hunters": 6, "lock_chance": 0.05,
        "joke": "office lunch bag; the whiskey is 'for clients'",
        "tale_ru": "Дед держал тут коллекцию… обедов с 2009-го. Сумка пахнет принтером и амбициями. Аукционист клянётся, что внутри опционы. Внутри — папка «Налоги 2009».",
        "tale_en": "Grandpa kept a collection of… lunches from 2009. The bag smells of toner and ambition. Auctioneer swears there are stock options inside. There is a Taxes 2009 folder.",
        "docs_ru": "ОПИСЬ (сдал бухгалтер, смена ночная):\n— сумка спорт, пятно от борща\n— ноут 2005, вентилятор орёт\n— папка «Налоги 2009»\n— виски «для клиентов» (клиентов нет)\n— купюра закладкой в «Аукционах для чайников»",
        "docs_en": "MANIFEST (night-shift accountant intake):\n— gym bag, borscht stain\n— 2005 laptop, fan screaming\n— Taxes 2009 folder\n— whiskey «for clients» (no clients)\n— a bill bookmarking Auctions for Dummies",
        "spawns": [
            S("bag_gym", -0.38, 0, -0.36, 16, nested=["tool_lighter", "cash_10"]),
            S("laptop_2005", 0.36, 0, -0.36, -10),
            S("folder_tax_2009", 0.08, 0, -0.08, 8),
            S("whiskey_cheap", -0.44, 0, 0.08, 4),
            S("book_dummies", 0.44, 0, 0.10, 70),
            S("cup_okayest", -0.14, 0, 0.18, -6),
            S("phone_flip", 0.20, 0, 0.20, 12),
            S("bill_coupon", -0.48, 0, 0.40, 0),
            S("frame_photo_cat", 0.06, 0, 0.46, 22),
            S("water_bottle", 0.46, 0, 0.42, 8),
            S("perfume_cheap", -0.22, 0, 0.44, 14),
        ],
    })

    lots.append({
        "id": "hangar_10", "district": "HANGAR", "kind": "BAG", "order": 10,
        "min_bid": 10, "info": "SLIT", "pacing": "JACKPOT",
        "preview": 16, "clearout": 80, "hunters": 6, "lock_chance": 0.08,
        "joke": "slit shows a tote; Boris the hamster is behind the jewelry box",
        "tale_ru": "Щель врёт: видна авоська. Хозяин шептал, что возит «питомца для души». Борис видел вещи. Борис молчит. Шкатулка играет одну ноту — ту самую.",
        "tale_en": "The slit lies: you see a tote. Owner whispered he traveled with a «soul pet». Boris has seen things. Boris says nothing. The music box plays one note — THE note.",
        "docs_ru": "ОПИСЬ (сдал сосед снизу, орёт):\n— хомяк «Борис», живой\n— шкатулка бархат + кольцо\n— авоська «Спасём планету»\n— купюры закладкой в дневнике\nПримечание: не кормить с молотка.",
        "docs_en": "MANIFEST (downstairs neighbor, yelling):\n— hamster «Boris», alive\n— velvet box + a ring\n— Save the Planet tote\n— bills bookmarking a diary\nNote: do not feed from the gavel.",
        "spawns": [
            S("bag_tote", -0.42, 0, -0.38, 18, nested=["cash_50"]),
            S("jewelry_box_velvet", 0.44, 0, -0.38, -12, nested=["ring_wedding"], locked=1),
            S("hamster_boris", 0.00, 0, 0.28, 20),
            S("camera_polaroid", 0.44, 0, 0.08, -16),
            S("book_diary", -0.44, 0, 0.12, 68, nested=["cash_20"]),
            S("cup_soviet_gold", 0.18, 0, -0.08, 8),
            S("letter_love", -0.12, 0, 0.48, 6),
            S("perfume_vintage", 0.44, 0, 0.42, 0),
            S("frame_photo_cat", -0.44, 0, 0.44, 28),
        ],
    })

    lots.append({
        "id": "hangar_11", "district": "HANGAR", "kind": "BAG", "order": 11,
        "min_bid": 38, "info": "TALE", "pacing": "BUST",
        "preview": 12, "clearout": 60, "hunters": 6, "lock_chance": 0.0,
        "joke": "mystery box rattles; it's a mouse and a painted brick",
        "tale_ru": "Коробка подписана «НЕ ОТКРЫВАТЬ». Хозяин клялся, что внутри клад Наполеона. Наполеон, если что, носил носок. Мышь уже провела инвентаризацию.",
        "tale_en": "The box says DO NOT OPEN. Owner swore Napoleon's hoard was inside. Napoleon, for the record, wore a sock. The mouse already did inventory.",
        "docs_ru": "ОПИСЬ №11 (печать «особо ценное» кривая):\n1× Слиток (краска «золото»)\n1× Носок (пара не найдена)\n1× Мышь (жила, жива)\n1× Билет лотереи (не стёрт)\nПодпись: «классика жанра».",
        "docs_en": "INVENTORY #11 (the «high value» stamp is crooked):\n1× Gold bar (gold paint)\n1× Sock (pair not found)\n1× Mouse (was living, still is)\n1× Lottery ticket (unscratched)\nSigned: «a classic».",
        "spawns": [
            S("box_mystery", 0.00, 0, -0.32, 10, nested=["mouse_live"], dirt=0.7),
            S("gold_bar_painted", 0.40, 0, 0.06, 4, dirt=0.6),
            S("sock_single", -0.44, 0, 0.04, -8, dirt=0.85),
            S("hat_tinfoil", 0.44, 0, -0.18, 35),
            S("plant_pot_dead", -0.44, 0, -0.20, -12, dirt=0.8),
            S("rag_dirty", -0.18, 0, 0.20, 20, dirt=0.9),
            S("bill_lottery", 0.18, 0, 0.22, 6),
            S("jar_unknown_stuff", 0.44, 0, 0.38, 8, dirt=0.7),
            S("poster_missing_cat", 0.00, 0, 0.46, 8),
            S("candle_stub", -0.44, 0, 0.40, 0, dirt=0.5),
        ],
    })

    lots.append({
        "id": "hangar_12", "district": "HANGAR", "kind": "BAG", "order": 12,
        "min_bid": 16, "info": "DOCS", "pacing": "LEAN",
        "preview": 15, "clearout": 74, "hunters": 6, "lock_chance": 0.05,
        "joke": "docs list a Canun DSLR; the bag has a Polaroyd and a Zenith",
        "tale_ru": "Фотограф снимал свадьбы в Сочи. Говорил, что объектив стоит как квартира. Объектив остался в Сочи. В сумке — Polaroyd и томик энциклопедии.",
        "tale_en": "The photographer shot weddings in Sochi. Said the lens cost as much as a flat. The lens stayed in Sochi. The bag has a Polaroyd and an encyclopedia volume.",
        "docs_ru": "ОПИСЬ (сдал администратор ЗАГСа):\n— сумка рабочая, запах проявителя\n— зеркалка «Кэнун» (в описи есть, в сумке нет)\n— Polaroyd + Зенит\n— диск «Для тебя»\n— фото с автографом «Тим Круз»",
        "docs_en": "MANIFEST (registry-office clerk intake):\n— work bag, developer smell\n— Canun DSLR (on the sheet, not in the bag)\n— Polaroyd + Zenith\n— a «For You» mix CD\n— signed photo of «Tim Cruze»",
        "spawns": [
            S("bag_work", -0.38, 0, -0.36, 14, nested=["cd_mixtape", "cash_5"]),
            S("camera_polaroid", 0.40, 0, -0.36, -12),
            S("camera_film_old", 0.10, 0, 0.02, 18),
            S("book_encyclopedia", 0.44, 0, 0.16, 88),
            S("cup_thermos", -0.42, 0, 0.16, -8),
            S("letter_aunt", 0.16, 0, 0.28, 4),
            S("frame_photo_signed_actor", -0.12, 0, 0.46, 10),
            S("tablet_kids", 0.42, 0, 0.42, 16),
            S("candle_scented", -0.44, 0, 0.42, 0),
        ],
    })

    lots.append({
        "id": "hangar_13", "district": "HANGAR", "kind": "BAG", "order": 13,
        "min_bid": 12, "info": "PHOTOS", "pacing": "JACKPOT",
        "preview": 17, "clearout": 82, "hunters": 6, "lock_chance": 0.1,
        "joke": "photos advertise Ming and a gold bar; the hollow book holds a crypto stick",
        "photos": ["suitcase_plastic", "vase_ming", "gold_bar", "camera_polaroid"],
        "tale_ru": "Чемодан «с секретом». Хозяин кричал про вазу Мин и слиток. Секрет — книга-тайник. Пароль от кошелька был на стикере. Стикер отклеился.",
        "tale_en": "A suitcase «with a secret». Owner yelled about a Ming vase and a gold bar. The secret is a hollow book. The wallet password was on a sticker. The sticker fell off.",
        "docs_ru": "ОПИСЬ (таможня, печать смазана):\n— чемодан пластик\n— ваза Мин — НЕТ\n— слиток — НЕТ\n— флешка «Кошелёк НЕ ТРОГАТЬ»\n— кольцо в музыкальной шкатулке",
        "docs_en": "MANIFEST (customs, smudged stamp):\n— plastic suitcase\n— Ming vase — NO\n— gold bar — NO\n— USB: Wallet DO NOT TOUCH\n— a ring in a music box",
        "spawns": [
            S("suitcase_plastic", 0.00, 0, -0.36, 8, nested=["book_hollow", "usb_crypto"]),
            S("jewelry_box_music", 0.44, 0, 0.02, -10, nested=["ring_diamond"]),
            S("camera_polaroid", -0.44, 0, 0.02, 20),
            S("bag_tote", -0.44, 0, 0.36, 16, nested=["cash_50"]),
            S("letter_treasure", 0.14, 0, 0.22, 4),
            S("cup_okayest", 0.44, 0, 0.38, -6),
            S("perfume_cheap", 0.18, 0, 0.48, 8),
            S("book_diary", 0.00, 0, 0.48, 70),
        ],
    })

    lots.append({
        "id": "hangar_14", "district": "HANGAR", "kind": "BAG", "order": 14,
        "min_bid": 20, "info": "DOOR15", "pacing": "LEAN",
        "preview": 15, "clearout": 76, "hunters": 6, "lock_chance": 0.05,
        "joke": "school-kitchen crossover: thermos, souvenir plate, a tote with a ten",
        "tale_ru": "Сумка с вокзала. Хозяин бежал на электричку и забыл жизнь. В жизни остались термос, тарелка «Привет из Сочи» и купюра в авоське. Сочи не отвечает.",
        "tale_en": "A bag from the station. Owner ran for a commuter train and forgot a life. The life left a thermos, a Greetings-from-Sochi plate, and a ten in a tote. Sochi does not reply.",
        "docs_ru": "ОПИСЬ (сдал кассир камеры хранения):\n— рюкзак школьный\n— тарелка сувенир\n— термос, вода, одеколон\n— авоська с десяткой\n— машинка «Хот Вилз» (коллекционная — нет)",
        "docs_en": "MANIFEST (left-luggage cashier):\n— school backpack\n— souvenir plate\n— thermos, water, cologne\n— tote with a ten\n— Hot Wheelz car (collectible — no)",
        "spawns": [
            S("backpack_school", -0.36, 0, -0.34, 12, nested=["usb_cat_videos", "cash_5"]),
            S("plate_souvenir", 0.40, 0, -0.36, 14),
            S("cup_thermos", -0.42, 0, 0.06, -8),
            S("water_bottle", 0.10, 0, 0.00, 0),
            S("book_cookbook", 0.44, 0, 0.08, 78),
            S("bag_tote", -0.44, 0, 0.34, 20, nested=["cash_10"]),
            S("candle_scented", 0.16, 0, 0.22, 6),
            S("hat_trucker", 0.46, 0, 0.36, 22),
            S("perfume_cheap", 0.22, 0, 0.48, 10),
            S("toy_car_hotwheelz", 0.00, 0, 0.48, -14),
        ],
    })

    # =====================================================================
    # STORAGE 13–22   continue … L | L J B L J L B L J L
    # 8 STORAGE + 2 LOCKER     broom on 15, 18, 19     dark on 15, 19, 21
    # =====================================================================

    lots.append({
        "id": "storage_13", "district": "STORAGE", "kind": "STORAGE", "order": 13,
        "min_bid": 95, "info": "SLIT", "pacing": "LEAN",
        "preview": 15, "clearout": 155, "hunters": 6, "lock_chance": 0.20,
        "broom": False, "dark": False,
        "joke": "slit shows a kettle; the paint cans are doing the real talking",
        "tale_ru": "Щель показывает чайник. Хозяин «делал ремонт и бросил». Краска не бросила его. Масло моторное стоит как почётный гость. Метлу не просили — ещё.",
        "tale_en": "The slit shows a kettle. Owner «started a renovation and quit». The paint did not quit him. Engine oil stands there like a guest of honor. No broom tax. Yet.",
        "docs_ru": "ЯЧЕЙКА 13 — КУХНЯ/РЕМОНТ:\nЧайник — 1\nМикроволновка жёлтая — 1\nКраска красная/синяя — 2\nМасло моторное — 1\nКоробки «хрупкое» у двери — да, они",
        "docs_en": "UNIT 13 — KITCHEN/RENO:\nKettle — 1\nYellowed microwave — 1\nRed/blue paint — 2\nEngine oil — 1\nFRAGILE boxes at the door — yes, those",
        "spawns": box_wall_front(1.12) + [
            S("dresser_ikeya", -0.85, 0, -1.10, 6, nested=["tshirt_ironic", "cash_10"]),
            S("fridge_mini", 1.10, 0, -1.10, -8),
            S("microwave_yellow", 0.15, 0, -1.12, 4),
            S("kettle_electric", 0.70, 0, -0.55, 12),
            S("paint_red", -1.15, 0, -0.40, 0),
            S("paint_blue", -0.85, 0, -0.40, 8),
            S("oil_jug_engine", 1.15, 0, -0.40, 14),
            S("chair_plastic", 0.20, 0, -0.35, 22),
            S("plant_pot_cactus", 1.20, 0, 0.20, 0),
            S("plate_stack_canteen", -0.90, 0, 0.25, 6),
            S("cup_thermos", -0.50, 0, 0.30, -10),
            S("radio_alarm", 0.55, 0, 0.28, 8),
        ] + cups(0.70, 0.35, 2, 2, "cup_okayest"),
    })

    lots.append({
        "id": "storage_14", "district": "STORAGE", "kind": "STORAGE", "order": 14,
        "min_bid": 70, "info": "TALE", "pacing": "JACKPOT",
        "preview": 15, "clearout": 180, "hunters": 7, "lock_chance": 0.22,
        "broom": False, "dark": False,
        "joke": "auctioneer talks about a magician; the maybe-master is face to the wall",
        "tale_ru": "Дед держал тут коллекцию… «неизвестного мастера». Сам дед неизвестный. Хомяк Валера люкс сидит как охранник. Виски на дне ящика — старше соседа.",
        "tale_en": "Grandpa kept a collection of… an unknown master. Grandpa is also unknown. Deluxe hamster Valera sits like security. The whiskey in the crate is older than the neighbor.",
        "docs_ru": "ЯЧЕЙКА 14 — ЖИВОПИСЬ:\nКартина «мастер?» — 1 (к стене)\nХомяк Валера люкс — 1\nЧемодан кожа + купюры\nВиски в ящике\nКоробки у двери — отвлекающий манёвр",
        "docs_en": "UNIT 14 — PAINTING:\n«Master?» painting — 1 (face to wall)\nValera deluxe hamster — 1\nLeather suitcase + bills\nWhiskey in a crate\nDoor boxes — a decoy",
        "spawns": box_wall_front(1.12) + [
            S("painting_maybe_master", 0.00, 0, -1.20, 4),
            S("hamster_cage_deluxe", -1.10, 0, -1.15, 16),
            S("suitcase_leather", 1.05, 0, -1.10, -6, nested=["book_hollow", "cash_100"], locked=1),
            S("crate_wooden", -1.10, 0, -0.45, 8, nested=["whiskey_single_malt"]),
            S("jewelry_box_velvet", 1.10, 0, -0.45, 12, nested=["ring_class"]),
            S("lamp_table_banker", 0.55, 0, -0.50, -10),
            S("nightstand_deco", 0.20, 0, 0.20, 8, nested=["letter_love"]),
            S("book_first_edition", -0.55, 0, 0.25, 70),
            S("plant_pot_bonsai", 1.20, 0, 0.25, 0),
            S("vase_soviet_crystal", -1.15, 0, 0.30, 6),
        ],
    })

    lots.append({
        "id": "storage_15", "district": "STORAGE", "kind": "STORAGE", "order": 15,
        "min_bid": 380, "info": "DOCS", "pacing": "BUST",
        "preview": 15, "clearout": 150, "hunters": 6, "lock_chance": 0.18,
        "broom": True, "dark": True,
        "joke": "docs promise antiques; the dark unit is mice, bricks, and a broom tax",
        "tale_ru": "Смотритель выключил свет «чтобы патина». Патины нет. Есть мыши и кирпичи. Метлу просят заранее — залог любят больше лота.",
        "tale_en": "Caretaker killed the lights «for the patina». No patina. There are mice and bricks. They want a broom up front — they love the deposit more than the lot.",
        "docs_ru": "ЯЧЕЙКА 15 — АНТИКВАРИАТ (темно, печать мокрая):\nВаза Мин — 1\nСлиток — 3\nЧасы Ролекс — 1\nПримечание: не включать свет. Не открывать коробки. Не дышать.",
        "docs_en": "UNIT 15 — ANTIQUES (dark, wet stamp):\nMing vase — 1\nGold bar — 3\nRolecks — 1\nNote: do not turn on the light. Do not open boxes. Do not breathe.",
        "spawns": [
            S("mattress_stained", 0.00, 0, -1.00, 0, dirt=0.85),
            S("vase_ming_fake", 1.22, 0, -1.15, 8, dirt=0.6),
            S("gold_bar_painted", -0.25, 0, -0.15, 4, dirt=0.5),
            S("gold_bar_painted", 0.25, 0, -0.12, -6, dirt=0.5),
            S("box_mystery", -1.15, 0, -0.20, 10, nested=["mouse_live"], dirt=0.7),
            S("box_small_mystery", 1.18, 0, -0.25, -8, nested=["mouse_white"], dirt=0.6),
            S("brick_red", -0.90, 0, 0.30, 0, dirt=0.4),
            S("brick_red", -0.50, 0, 0.34, 8, dirt=0.4),
            S("brick_red", -0.10, 0, 0.32, -6, dirt=0.4),
            S("brick_red", 0.30, 0, 0.36, 12, dirt=0.4),
            S("brick_lego_giant", 1.15, 0, 0.25, 4),
            S("plant_pot_dead", 1.22, 0, 0.85, 0, dirt=0.8),
            S("rag_dirty", -1.15, 0, 0.75, 18, dirt=0.9),
            S("mop_gross", 1.25, 0, 1.15, 6, dirt=0.85),
            S("tool_broom", 1.28, 0, -0.55, 8),
            S("paint_half_dried", 0.75, 0, 0.70, 0, dirt=0.7),
            S("chair_plastic", -0.70, 0, 1.05, 22, dirt=0.5),
            S("hat_tinfoil", 0.50, 0, 1.10, 30),
            S("sock_single", -0.20, 0, 1.15, 10, dirt=0.8),
            S("safe_empty_open", 0.00, 0, 0.85, 8, nested=["letter_debt"], dirt=0.6),
        ],
    })

    lots.append({
        "id": "storage_16", "district": "STORAGE", "kind": "LOCKER", "order": 16,
        "min_bid": 88, "info": "DOOR15", "pacing": "LEAN",
        "preview": 15, "clearout": 125, "hunters": 6, "lock_chance": 0.22,
        "broom": False, "dark": False,
        "joke": "locker of a DJ who peaked in 1994",
        "tale_ru": "Локер диджея. Он пикнул в девяносто четвёртом. Кассета «Лето 94» ещё крутится в голове. Виски на дне — недопитый, как карьера.",
        "tale_en": "A DJ's locker. He peaked in ninety-four. The Summer '94 tape still spins in his head. The whiskey at the bottom is half-drunk, like the career.",
        "docs_ru": "ЛОКЕР 16. Сдал охрана клуба «Плазма»:\nБумбокс 90-х — 1\nКассеты / диски — стопка\nРюкзак + худи\nВиски недопитый\nПульт от неизвестно чего",
        "docs_en": "LOCKER 16. Intake: security at Club Plasma:\n'90s boombox — 1\nTapes / discs — a stack\nBackpack + hoodie\nHalf-drunk whiskey\nRemote to nothing",
        "spawns": [
            S("boombox_90s", 0.00, 0.00, -0.16, 8),
            S("backpack_hiking", 0.00, 0.28, -0.08, 10, nested=["cassette_mixtape", "cash_10"]),
            S("hoodie_grey", 0.00, 1.02, 0.10, 6),
            S("hat_fedora", 0.00, 1.14, -0.22, 24),
            S("cd_mixtape", 0.28, 0.00, 0.28, 0),
            S("cd_windows_98", -0.28, 0.00, 0.28, 8),
            S("cassette_answering", 0.00, 0.00, 0.30, 4),
            S("whiskey_half", 0.30, 0.28, 0.22, 0),
            S("remote_mystery", -0.30, 0.28, 0.22, 12),
            S("watch_kasio", -0.28, 1.02, 0.28, 40),
        ],
    })

    lots.append({
        "id": "storage_17", "district": "STORAGE", "kind": "STORAGE", "order": 17,
        "min_bid": 75, "info": "PHOTOS", "pacing": "JACKPOT",
        "preview": 15, "clearout": 185, "hunters": 8, "lock_chance": 0.24,
        "broom": False, "dark": False,
        "joke": "photos show a cracked plasma; the real Ming sits behind the door wall",
        "photos": ["tv_plasma_cracked", "box_moving", "vase_ming_fake", "gold_bar"],
        "tale_ru": "Фото врёт треснутой плазмой. Настоящая Мин стоит у задней стены, как будто стесняется. Сейф старый — гнездо. Виски 50 лет смотрит на вас старше вашего отца.",
        "tale_en": "The photos lie with a cracked plasma. The real Ming stands at the back wall, shy. The old safe is a nest. The 50-year whiskey looks at you older than your dad.",
        "docs_ru": "ЯЧЕЙКА 17 — «хлам» (фотограф моргнул):\nВаза Мин — 1 (не на фото)\nСейф старый — 1\nВиски 50 лет — 1\nПлазма треснутая — нет, это враньё",
        "docs_en": "UNIT 17 — «junk» (photographer blinked):\nMing vase — 1 (not in the photos)\nOld safe — 1\n50-year whiskey — 1\nCracked plasma — no, that is a lie",
        "spawns": box_wall_front(1.12) + [
            S("vase_ming", 0.00, 0, -1.18, 10),
            S("safe_old", 1.05, 0, -1.10, -8, nested=["cash_100", "cash_100"], locked=1),
            S("whiskey_50yo", -1.10, 0, -1.12, 6),
            S("lamp_table_tiffany", -1.10, 0, -0.45, 12),
            S("nightstand_deco", 0.55, 0, -0.50, 8, nested=["watch_pocket"]),
            S("book_first_edition", 0.10, 0, 0.15, 70),
            S("teapot_silver", 1.15, 0, 0.20, -6),
            S("statue_david", -1.15, 0, 0.25, 14),
            S("plant_pot_bonsai", 1.20, 0, 0.65, 0),
        ],
    })

    lots.append({
        "id": "storage_18", "district": "STORAGE", "kind": "STORAGE", "order": 18,
        "min_bid": 140, "info": "SLIT", "pacing": "LEAN",
        "preview": 15, "clearout": 170, "hunters": 7, "lock_chance": 0.20,
        "broom": True, "dark": False,
        "joke": "slit flashes a tire; the gasoline is one nudge from a story",
        "tale_ru": "Мастерская без мастера. Бензин стоит у прохода как вопрос. Смотритель просит метлу — «а то запах». Запах не выметешь.",
        "tale_en": "A workshop without a master. Gasoline stands in the aisle like a question. Caretaker wants a broom — «for the smell». You cannot sweep a smell.",
        "docs_ru": "ЯЧЕЙКА 18 — СТО:\nПолка + ящик дедов\nШуруповёрт «Макито»\nКанистра бензина — 1\nМасло — 1\nМетла обязательна, залог любят",
        "docs_en": "UNIT 18 — GARAGE-SHOP:\nShelf + grandpa's toolbox\nMakito drill\nGasoline canister — 1\nOil — 1\nBroom required, they love the deposit",
        "spawns": [
            S("shelf_garage", -1.00, 0, -1.10, 0),
            S("toolbox_grandpa", -1.00, 1.22, -1.10, 8, nested=["wrench_monkey", "cash_20"]),
            S("toolbox_red", 0.20, 0, -1.12, -10, nested=["hammer_rusty", "tool_nails"]),
            S("engine_lawnmower", 1.05, 0, -1.00, 12),
            S("drill_cordless", -0.65, 0, -0.48, 18),
            S("gasoline_canister", 1.15, 0, -0.40, 10),
            S("oil_jug_engine", 0.55, 0, -0.42, 16),
            S("paint_green", -0.15, 0, -0.45, 0),
            S("tire_bald", -1.05, 0, 0.30, 8),
            S("tire_bald", -1.05, 0.24, 0.34, -6),
            S("fan_industrial", 1.15, 0, 0.25, 8),
            S("wrench_giant", 0.20, 0, 0.30, 38),
            S("box_moving", -0.95, 0, 1.10, 6, nested=["tape_colored"]),
            S("crate_military", 0.15, 0, 1.08, -4, nested=["gun_gag_cap"], locked=1),
            S("chair_plastic", 1.05, 0, 1.05, 20),
            S("tool_broom", 1.28, 0, 0.65, 8),
            S("rag_dirty", -1.20, 0, 0.70, 16, dirt=0.6),
            S("bucket_kfs", -0.55, 0, 0.70, 0),
            S("nail_box_rusty", 0.50, 0, 0.68, 4),
            S("flashlight_big", -0.15, 0, 0.68, 12),
        ],
    })

    lots.append({
        "id": "storage_19", "district": "STORAGE", "kind": "STORAGE", "order": 19,
        "min_bid": 350, "info": "TALE", "pacing": "BUST",
        "preview": 15, "clearout": 145, "hunters": 6, "lock_chance": 0.16,
        "broom": True, "dark": True,
        "joke": "tale of a mattress bank; the mice already withdrew",
        "tale_ru": "Дед не доверял банкам. Дед был прав — и мёртв. Матрас «Сбербанк» уже пуст. Мыши оформили вклад. Метлу всё равно просят.",
        "tale_en": "Grandpa didn't trust banks. Grandpa was right — and dead. The mattress bank is already empty. The mice made a withdrawal. They still want a broom.",
        "docs_ru": "ЯЧЕЙКА 19 — «СБЕРКАССА»:\nМатрас с памятью (пустой)\nМыши — 2\nКирпичи «золото» — несколько\nСейф вскрытый + письмо о долге\nСвет не включать: мыши стесняются",
        "docs_en": "UNIT 19 — «SAVINGS»:\nMemory mattress (empty)\nMice — 2\n«Gold» bricks — several\nCracked safe + a debt letter\nDo not turn on the light: the mice are shy",
        "spawns": [
            S("mattress_money", 0.00, 0, -1.00, 0, dirt=0.7),
            S("pillow_flat", 0.40, 0.24, -0.95, 14, dirt=0.6),
            S("mouse_live", -1.20, 0, 0.05, 8),
            S("mouse_white", 1.22, 0, 0.55, -12),
            S("box_moving", -0.90, 0, 1.10, 8, dirt=0.5),
            S("box_amazoom", 0.05, 0, 1.12, -6, dirt=0.5),
            S("crate_fruit", 0.95, 0, 1.08, 12, dirt=0.6),
            S("gold_bar_painted", -0.50, 0, 0.75, 4, dirt=0.5),
            S("gold_bar_painted", 0.50, 0, 0.75, -8, dirt=0.5),
            S("brick_red", -1.10, 0, 0.30, 0, dirt=0.4),
            S("brick_red", 1.10, 0, 0.32, 10, dirt=0.4),
            S("safe_empty_open", 0.00, 0, 0.15, 8, nested=["letter_debt"], dirt=0.7),
            S("plant_pot_dead", -1.20, 0, -0.20, 0, dirt=0.85),
            S("plant_pot_dead", 1.20, 0, -0.25, 8, dirt=0.85),
            S("rag_dirty", -0.70, 0, 0.70, 20, dirt=0.9),
            S("mop_gross", 1.25, 0, 0.70, 6, dirt=0.85),
            S("tool_broom", 1.28, 0, 0.15, 8),
            S("bucket_kfs", -1.15, 0, 0.70, 0, dirt=0.6),
            S("hat_tinfoil", -0.20, 0, 0.70, 28),
            S("watch_rolecks_fake", 0.55, 0, -1.15, 18),
        ],
    })

    lots.append({
        "id": "storage_20", "district": "STORAGE", "kind": "LOCKER", "order": 20,
        "min_bid": 100, "info": "DOCS", "pacing": "LEAN",
        "preview": 15, "clearout": 130, "hunters": 6, "lock_chance": 0.28,
        "broom": False, "dark": False,
        "joke": "docs list a katana; the locker has a spy suitcase and a cafeteria menu",
        "tale_ru": "Шпионский локер. Папка «совершенно секретно» — меню столовой. Чемодан не открывается без отмычки. Катана снова не влезла.",
        "tale_en": "A spy locker. The TOP SECRET folder is a cafeteria menu. The suitcase will not open without a pick. The katana, once again, did not fit.",
        "docs_ru": "ЛОКЕР 20. Сдал человек в плаще (плащ унёс):\nЧемодан шпионский — 1\nПапка секретно — меню\nТелефон одноразовый\nФлешка без подписи\nКатана — нет, ушла в порт",
        "docs_en": "LOCKER 20. Intake: man in a trench (trench left):\nSpy briefcase — 1\nSecret folder — a menu\nBurner phone\nUnmarked USB\nKatana — no, walked to the port",
        "spawns": [
            S("suitcase_spy", 0.00, 0.00, -0.16, 8, nested=["usb_unmarked", "document_passport_fake"], locked=1),
            S("folder_top_secret", 0.00, 0.26, 0.06, 6),
            S("folder_blueprints", 0.00, 0.32, -0.10, -4),
            S("phone_burner", 0.28, 0.00, 0.28, 12),
            S("jacket_leather", 0.00, 0.70, 0.08, 8),
            S("hat_fedora", 0.00, 0.82, -0.22, 22),
            S("lockpick_hairpin", -0.28, 0.00, 0.28, 0),
            S("watch_kasio", 0.00, 1.05, 0.22, 36),
            S("lighter_zipppo", 0.28, 0.26, 0.22, 8),
        ],
    })

    lots.append({
        "id": "storage_21", "district": "STORAGE", "kind": "STORAGE", "order": 21,
        "min_bid": 80, "info": "DOOR15", "pacing": "JACKPOT",
        "preview": 15, "clearout": 190, "hunters": 8, "lock_chance": 0.26,
        "broom": False, "dark": True,
        "joke": "dark unit; plasma at the back, diamond ring in the oak dresser",
        "tale_ru": "Темно, потому что лампочка «на продажу». Плазма 55 у задней стены. В дубовом комоде — кольцо с очень уверенным стеклом. Или бриллиантом. Не включайте свет — и так видно.",
        "tale_en": "It's dark because the bulb is «for sale». A 55-inch plasma at the back wall. In the oak dresser — a ring of very confident glass. Or a diamond. Don't turn on the light — you can see anyway.",
        "docs_ru": "ЯЧЕЙКА 21 — ТЕХНИКА:\nПлазма 55 «Самсонг» — 1\nКомод дуб + кольцо\nЛампа Тиффани\nТемно: лампочку сняли и куда-то дели",
        "docs_en": "UNIT 21 — TECH:\n55-inch Samsong plasma — 1\nOak dresser + a ring\nTiffanny lamp\nDark: they took the bulb and lost it",
        "spawns": box_wall_front(1.12) + [
            S("plasma_55", 0.00, 0, -1.18, 4),
            S("dresser_oak", -0.95, 0, -0.25, 88, nested=["ring_diamond", "necklace_pearl"]),
            S("lamp_table_tiffany", 1.05, 0, -1.08, -10),
            S("jewelry_box_music", 1.05, 0.48, -1.08, 12, nested=["ring_wedding"]),
            S("nightstand_deco", 1.10, 0, -0.35, 8, nested=["watch_pocket"]),
            S("laptop_macbuk", 0.35, 0, 0.20, 14),
            S("camera_dslr", -0.40, 0, 0.22, -16),
            S("statue_david", 1.20, 0, 0.30, 10),
            S("book_first_edition", -0.35, 0, 0.55, 68),
        ],
    })

    lots.append({
        "id": "storage_22", "district": "STORAGE", "kind": "STORAGE", "order": 22,
        "min_bid": 160, "info": "PHOTOS", "pacing": "LEAN",
        "preview": 15, "clearout": 165, "hunters": 7, "lock_chance": 0.18,
        "broom": False, "dark": False,
        "joke": "photos include a MacBuk; the unit is kids junk and a GameCubik",
        "photos": ["dresser_kids", "laptop_macbuk", "plasma_55", "toy_bear_giant"],
        "tale_ru": "Ячейка ребёнка, которому сорок. Приставка «ГеймКубик», Барбее, матрас с машинками. На фото — МакБук. МакБук уехал к старшему брату.",
        "tale_en": "A child's unit, and the child is forty. A GameCubik, a Barbee, a mattress with cars. The photos show a MacBuk. The MacBuk moved in with the older brother.",
        "docs_ru": "ЯЧЕЙКА 22 — ДЕТСКАЯ:\nКомод розовый\nПриставка ГеймКубик\nКукла Барбее + мишка\nМакБук — в описи фото, не в ячейке",
        "docs_en": "UNIT 22 — KIDS:\nPink dresser\nGameCubik console\nBarbee + a teddy\nMacBuk — in the photo sheet, not in the unit",
        "spawns": [
            S("dresser_kids", -0.90, 0, -1.10, 6, nested=["doll_barbee", "toy_car_hotwheelz"]),
            S("mattress_kids", 0.35, 0, -1.05, 8),
            S("console_gamecubik", 1.10, 0, -1.10, -8),
            S("tablet_kids", 1.10, 0.12, -0.70, 12),
            S("toy_bear_pink", -1.15, 0, -0.40, 10),
            S("toy_car_rc", 0.20, 0, -0.40, 16),
            S("ball_beach", 0.85, 0, -0.35, 0),
            S("keyboard_kids", -0.20, 0, 0.20, 4),
            S("lamp_table_lava", 1.10, 0, 0.20, 8),
            S("box_small_shoes", -1.10, 0, 0.25, 10, nested=["cassette_mixtape"]),
            S("chair_plastic", 0.40, 0, 0.25, 24),
            S("plant_pot_plastic", 1.20, 0, 0.65, 0),
            S("box_moving", -0.90, 0, 1.10, 8, nested=["cup_okayest"]),
            S("box_amazoom", 0.05, 0, 1.12, -6, nested=["usb_novelty_sushi"]),
            S("crate_fruit", 0.95, 0, 1.08, 12, nested=["toy_car_hotwheelz"]),
            S("poster_band", -1.25, 0, 0.70, 88),
            S("skateboard_old", -0.40, 0, 0.70, 6),
            S("cup_novelty_toilet", 0.20, 0, 0.70, 0),
        ],
    })

    # =====================================================================
    # GARAGES 09–18   continue … L | L J B L J L B L J L
    # broom on 11, 12, 15, 16, 18     min_bid 400–2500
    # =====================================================================

    def g_door_boxes():
        return [
            S("box_moving", 0.70, 0, 2.22, 8, nested=["plate_ikeya"]),
            S("box_amazoom", 1.50, 0, 2.20, -6, nested=["remote_tv"]),
            S("crate_fruit", 2.15, 0, 2.15, 12),
        ]

    def g_bricks():
        return brick_stack((-2.05, 0.0, 2.12), 3, 2, 2, (0.44, 0.065, 0.32), rot=3)

    lots.append({
        "id": "garages_09", "district": "GARAGES", "kind": "GARAGE", "order": 9,
        "min_bid": 480, "info": "DOOR15", "pacing": "LEAN",
        "preview": 24, "clearout": 260, "hunters": 7, "lock_chance": 0.22,
        "broom": False,
        "joke": "door-15 shows china; the leather sofa is all the way back",
        "tale_ru": "Переезд, который не доехал. Диван кожаный у задней стены, фарфор «Мейсенн» как будто ждёт гостей. Гостей нет. Есть кирпичи у ворот — классика района.",
        "tale_en": "A move that never arrived. Leather sofa against the back wall, Meissenn china waiting for guests. No guests. Bricks at the door — a district classic.",
        "docs_ru": "ГАРАЖ 09 — ПЕРЕЕЗД:\nДиван кожа — 1\nФарфор — 1\nХолодильник ретро + виски\nКирпичи у ворот — «временно»",
        "docs_en": "GARAGE 09 — MOVE:\nLeather sofa — 1\nChina — 1\nRetro fridge + whiskey\nBricks at the door — «temporary»",
        "spawns": g_bricks() + g_door_boxes() + [
            S("sofa_leather", 0.10, 0, -2.40, 4),
            S("fridge_retro", 2.00, 0, -2.15, -6, nested=["jar_pickles", "whiskey_cheap"]),
            S("dresser_oak", -2.05, 0, -1.00, 90, nested=["letter_love", "cash_20"]),
            S("wardrobe_ikeya", 2.00, 0, -0.20, 90, nested=["hoodie_grey", "shirt_hawaiian"]),
            S("chandelier_crystal", 0.10, 0, -1.00, 12),
            S("plate_stack_china", -1.55, 0, -0.15, 8),
            S("teapot_silver", -1.00, 0, -0.15, -8),
            S("lamp_floor_deco", 2.10, 0, -1.10, 8),
            S("mirror_baroque", 2.22, 0, 0.70, 90),
            S("sewing_singher", -1.75, 0, 0.70, 12),
            S("typewriter_old", -1.70, 0, 1.25, -8),
            S("bicycle_racing", 0.90, 0, 0.85, 0),
            S("plant_pot_bonsai", 2.10, 0, 1.40, 0),
            S("cup_soviet_gold", -1.20, 0, 0.40, 0),
            S("cup_soviet_gold", -0.95, 0, 0.42, 8),
            S("vase_ikeya", -0.60, 0, 0.40, 6),
            S("book_cookbook", -1.20, 0, 1.15, 74),
        ],
    })

    lots.append({
        "id": "garages_10", "district": "GARAGES", "kind": "GARAGE", "order": 10,
        "min_bid": 420, "info": "TALE", "pacing": "JACKPOT",
        "preview": 28, "clearout": 300, "hunters": 8, "lock_chance": 0.25,
        "broom": False,
        "joke": "tale about a palace; the 50-year whiskey and old safe are behind the brick pile",
        "tale_ru": "Хозяин сказал: «тут дворец». Дворца нет. Есть люстра дворцовая, виски старше вашего отца и сейф, который не любит гостей. Кирпичи у ворот — антураж.",
        "tale_en": "Owner said: «there's a palace in there». No palace. There is a palace chandelier, whiskey older than your dad, and a safe that hates guests. Bricks at the door — set dressing.",
        "docs_ru": "ГАРАЖ 10 — «ДВОРЕЦ»:\nЛюстра дворцовая — 1\nВиски 50 лет — 1\nСейф старый — 1 (заперт)\nРояля нет, есть пианино «Красный Октябрь»",
        "docs_en": "GARAGE 10 — «PALACE»:\nPalace chandelier — 1\n50-year whiskey — 1\nOld safe — 1 (locked)\nNo grand piano, there is a Red October upright",
        "spawns": g_bricks() + g_door_boxes() + [
            S("piano_upright", -0.70, 0, -2.35, 6),
            S("whiskey_50yo", 0.70, 0, -2.40, 8),
            S("safe_old", 1.90, 0, -2.25, -8, nested=["cash_500", "coin_jar_gold"], locked=1),
            S("chandelier_grand", 0.10, 0, -1.10, 14),
            S("dresser_oak", -2.05, 0, -0.70, 90, nested=["book_first_edition", "cash_100"]),
            S("bust_marble", 1.70, 0, -1.10, -10),
            S("vase_greek_amphora", 2.00, 0, -0.30, 6),
            S("rug_persian", 0.10, 0, 0.20, 8),
            S("lamp_table_tiffany", -1.70, 0, 0.50, 12),
            S("globe_bar", 2.00, 0, 0.80, -12, nested=["glass_shot_set"]),
            S("teapot_silver", -1.10, 0, 0.55, 8),
            S("necklace_gold_chain", 0.30, 0, 0.70, 28),
            S("plant_pot_bonsai", 2.10, 0, 1.40, 0),
        ],
    })

    lots.append({
        "id": "garages_11", "district": "GARAGES", "kind": "GARAGE", "order": 11,
        "min_bid": 2200, "info": "DOCS", "pacing": "BUST",
        "preview": 22, "clearout": 250, "hunters": 7, "lock_chance": 0.20,
        "broom": True,
        "joke": "docs list a V8 and a plasma; the bay is a smelly fridge, mice, painted gold",
        "tale_ru": "Опись на масляной бумаге обещает V8 и плазму. Бумага врёт лучше аукциониста. Холодильник помнит рыбу. Мыши помнят вас. Метла обязательна и бесполезна.",
        "tale_en": "The oily-paper manifest promises a V8 and a plasma. Paper lies better than the auctioneer. The fridge remembers a fish. The mice remember you. Broom required and useless.",
        "docs_ru": "ГАРАЖ 11 — МАСТЕРСКАЯ (печать «проверено»):\nМотор V8 — 1\nПлазма 55 — 1\nСлитки — 4\nПримечание: запах «нормальный». Мышей «нет».",
        "docs_en": "GARAGE 11 — WORKSHOP («verified» stamp):\nV8 engine — 1\n55-inch plasma — 1\nGold bars — 4\nNote: smell is «normal». Mice are «none».",
        "spawns": g_bricks() + [
            S("sofa_sagging", 0.10, 0, -2.40, 4, dirt=0.7),
            S("fridge_smelly", 2.00, 0, -2.10, -8, nested=["jar_pickles", "jar_unknown_stuff"], dirt=0.85),
            S("wardrobe_ikeya", 2.00, 0, -0.30, 90, dirt=0.4),
            S("clock_grandfather_broken", -2.15, 0, -1.90, 4, dirt=0.6),
            S("mattress_stained", -1.50, 0, 0.40, 0, dirt=0.85),
            S("gold_bar_painted", -0.40, 0, 1.50, 4, dirt=0.5),
            S("gold_bar_painted", 0.05, 0, 1.54, -8, dirt=0.5),
            S("gold_bar_painted", 0.50, 0, 1.48, 12, dirt=0.5),
            S("box_mystery", 1.40, 0, 1.55, 8, nested=["mouse_live"], dirt=0.7),
            S("mouse_white", 2.10, 0, 1.20, -10),
            S("barrel_rusty", 1.70, 0, 0.50, 10, dirt=0.8),
            S("barrel_rusty", 0.70, 0, 0.50, -6, dirt=0.8),
            S("anvil_cartoon", 0.00, 0, -0.40, 12),
            S("plant_pot_dead", -2.15, 0, 1.40, 0, dirt=0.85),
            S("mop_gross", 2.15, 0, 0.90, 6, dirt=0.9),
            S("tool_broom", 2.20, 0, 1.50, 8),
            S("rag_dirty", -0.90, 0, 1.50, 18, dirt=0.9),
            S("tv_plasma_cracked", 0.15, 0, -1.20, 8, dirt=0.4),
        ],
    })

    lots.append({
        "id": "garages_12", "district": "GARAGES", "kind": "GARAGE", "order": 12,
        "min_bid": 550, "info": "SLIT", "pacing": "LEAN",
        "preview": 26, "clearout": 280, "hunters": 8, "lock_chance": 0.25,
        "broom": True,
        "joke": "slit shows tires; the chrome V8 is not here, the lawnmower engine is",
        "tale_ru": "Щель — покрышки. Хозяин клялся, что тут мотор от Феррари. Тут мотор от газонокосилки. Бензин и масло ждут сюжета. Метлу просят из приличия.",
        "tale_en": "The slit is tires. Owner swore a Ferrari engine lived here. A lawnmower engine lives here. Gasoline and oil are waiting for a plot. They want a broom out of politeness.",
        "docs_ru": "ГАРАЖ 12 — СТО:\nМотор V8 — нет\nМотор газонокосилки — да\nКанистра + масло\nПокрышки лысые — стопка\nМетла обязательна",
        "docs_en": "GARAGE 12 — SHOP:\nV8 — no\nLawnmower engine — yes\nCanister + oil\nBald tires — a stack\nBroom required",
        "spawns": g_bricks() + g_door_boxes() + [
            S("engine_lawnmower", -1.70, 0, -2.30, 12),
            S("engine_block", 1.80, 0, -2.20, 10, dirt=0.5),
            S("sofa_sagging", 0.15, 0, -2.35, 4),
            S("toolbox_grandpa", -2.00, 0, -1.10, 8, nested=["drill_cordless", "cash_20"]),
            S("toolbox_red", -1.30, 0, -1.10, -8, nested=["hammer_rusty", "wrench_adjustable"]),
            S("gasoline_canister", 1.90, 0, -1.10, 10),
            S("oil_jug_engine", 1.30, 0, -1.05, 14),
            S("oil_barrel", 2.05, 0, -0.20, 6),
            S("tire_bald", -2.00, 0, 0.40, 8),
            S("tire_bald", -2.00, 0.24, 0.44, -6),
            S("tire_racing", 1.90, 0, 0.50, 8),
            S("fan_industrial", 2.05, 0, 1.20, 8),
            S("wrench_giant", 0.20, 0, 0.40, 36),
            S("shelf_garage", 0.15, 0, -1.15, 0),
            S("tool_broom", -2.20, 0, 1.40, 8),
            S("paint_gold", 0.70, 0, 0.40, 0),
            S("rag_dirty", -0.50, 0, 0.50, 16, dirt=0.5),
        ],
    })

    lots.append({
        "id": "garages_13", "district": "GARAGES", "kind": "GARAGE", "order": 13,
        "min_bid": 450, "info": "PHOTOS", "pacing": "JACKPOT",
        "preview": 30, "clearout": 320, "hunters": 8, "lock_chance": 0.25,
        "joke": "photos show bricks and a cracked plasma; the signed guitar is at the back",
        "photos": ["brick_red", "tv_plasma_cracked", "guitar_signed", "plasma_55"],
        "tale_ru": "На фото — кирпичи. За кирпичами — гитара с автографом «Курт». Или «Крут». В ящике деда — настоящие Ролексы и пятьсот. Сейф тоже не пустой.",
        "tale_en": "The photos are bricks. Behind the bricks — a guitar signed «Kurt». Or «Kool». Grandpa's toolbox holds a real Rolecks and a five-hundred. The safe is not empty either.",
        "docs_ru": "ГАРАЖ 13 — МУЗЫКА:\nГитара с автографом — 1\nСейф + ящик деда (заперты)\nКирпичи у ворот — да\nПлазма на фото — враньё",
        "docs_en": "GARAGE 13 — MUSIC:\nSigned guitar — 1\nSafe + grandpa's box (locked)\nBricks at the door — yes\nPlasma in the photos — a lie",
        "spawns": g_bricks() + g_door_boxes() + [
            S("guitar_signed", 0.80, 0, -2.40, 20),
            S("toolbox_grandpa", -1.90, 0, -2.30, 10, nested=["watch_rolecks_real", "cash_500"], locked=1),
            S("safe_old", 1.85, 0, -2.25, -8, nested=["cash_500"], locked=1),
            S("bust_marble", 0.00, 0, -2.35, 12),
            S("dresser_oak", 2.05, 0, -0.70, 90, nested=["cd_gold_record"]),
            S("anvil_iron", -2.05, 0, -1.10, 8),
            S("guitar_electric_pink", -1.70, 0, 0.50, -12),
            S("boombox_gold", 0.20, 0, 0.40, 6),
            S("trumpet_gold", 1.40, 0, 0.50, 68),
            S("ball_disco", 2.00, 0, 0.90, 0),
            S("poster_movie_1st", -2.20, 0, 0.80, 88),
            S("lamp_table_lava", 0.70, 0, 0.90, 8),
        ],
    })

    lots.append({
        "id": "garages_14", "district": "GARAGES", "kind": "GARAGE", "order": 14,
        "min_bid": 700, "info": "DOOR15", "pacing": "LEAN",
        "preview": 24, "clearout": 270, "hunters": 7, "lock_chance": 0.24,
        "broom": False,
        "joke": "door-15 diner: retro fridge, smart-ish TV, olive oil for some reason",
        "tale_ru": "Гараж-закусочная. Холодильник ретро знает рецепты. Смарт-ТВ знает ваши грехи — но это в другом лоте. Тут оливковое масло и сервиз. Кирпичи у двери — «меню».",
        "tale_en": "A diner garage. The retro fridge knows recipes. The smart TV knows your sins — that's another lot. Here: olive oil and a dinner set. Bricks at the door are the «menu».",
        "docs_ru": "ГАРАЖ 14 — ЗАКУСОЧНАЯ:\nХолодильник ретро — 1\nПлазма 32 — 1\nМасло оливковое — 1\nСервиз столовский\nДиван бархат (для VIP)",
        "docs_en": "GARAGE 14 — DINER:\nRetro fridge — 1\n32-inch plasma — 1\nOlive oil — 1\nCanteen plates\nVelvet sofa (VIP)",
        "spawns": g_bricks() + g_door_boxes() + [
            S("sofa_velvet", 0.15, 0, -2.40, -4),
            S("fridge_retro", 2.00, 0, -2.15, 6, nested=["jar_pickles"]),
            S("tv_plasma_32", 0.10, 0, -1.20, 8),
            S("wardrobe_ikeya", 2.00, 0, -0.25, 90, nested=["shirt_hawaiian"]),
            S("dresser_ikeya", -2.05, 0, -0.60, 90, nested=["tshirt_band"]),
            S("microwave_new", -1.50, 0, 0.50, -8),
            S("kettle_electric", -0.90, 0, 0.55, 10),
            S("oil_olive", 1.50, 0, 0.50, 0),
            S("plate_stack_canteen", 1.00, 0, 0.55, 6),
            S("chandelier_plastic", 0.10, 0, -0.30, 12),
            S("chair_plastic", -1.80, 0, 1.10, 20),
            S("chair_plastic", -1.10, 0, 1.10, -12),
            S("plant_pot_cactus", 2.10, 0, 1.30, 0),
            S("cup_okayest", 0.30, 0, 0.55, 0),
            S("cup_okayest", 0.55, 0, 0.58, 8),
            S("radio_soviet", -0.30, 0, 0.60, -14),
        ],
    })

    lots.append({
        "id": "garages_15", "district": "GARAGES", "kind": "GARAGE", "order": 15,
        "min_bid": 2400, "info": "TALE", "pacing": "BUST",
        "preview": 20, "clearout": 245, "hunters": 7, "lock_chance": 0.18,
        "broom": True,
        "joke": "clown graveyard: mannequin, sad clown painting, mice, broom tax",
        "tale_ru": "Цирк уехал. Костюм клоуна остался. Манекен поворачивает голову — возможно. Мыши не смеются. Метлу просят, как будто она лечит фобии скупщика.",
        "tale_en": "The circus left. The clown costume stayed. The mannequin turns its head — possibly. The mice are not laughing. They want a broom as if it cures a vendor's phobia.",
        "docs_ru": "ГАРАЖ 15 — РЕКВИЗИТ:\nКостюм клоуна — 1\nМанекен жуткий — 1\nКартина «грустный клоун»\nМыши — да\nЗолото — краска",
        "docs_en": "GARAGE 15 — PROPS:\nClown costume — 1\nCreepy mannequin — 1\nSad clown painting\nMice — yes\nGold — paint",
        "spawns": g_bricks() + [
            S("mannequin_creepy", 0.00, 0, -2.35, 8, dirt=0.4),
            S("costume_clown", 1.10, 0, -2.30, 170, dirt=0.3),
            S("shoe_clown", -1.10, 0, -2.35, 18, dirt=0.5),
            S("painting_sad_clown", 0.10, 0, -1.30, 4, dirt=0.4),
            S("sofa_sagging", 1.80, 0, -0.80, 90, dirt=0.7),
            S("fridge_smelly", -2.00, 0, -1.00, 6, nested=["jar_unknown_stuff"], dirt=0.85),
            S("box_mystery", -0.50, 0, 0.40, 8, nested=["mouse_live"], dirt=0.7),
            S("mouse_white", 0.40, 0, 0.45, -10),
            S("gold_bar_painted", 1.20, 0, 0.50, 4, dirt=0.5),
            S("gold_bar_painted", 1.60, 0, 0.52, -6, dirt=0.5),
            S("barrel_rusty", 2.00, 0, 1.20, 10, dirt=0.8),
            S("plant_pot_dead", -2.15, 0, 1.40, 0, dirt=0.85),
            S("mop_gross", 2.15, 0, 0.40, 6, dirt=0.9),
            S("tool_broom", -2.20, 0, 0.80, 8),
            S("rag_dirty", -1.40, 0, 0.50, 16, dirt=0.9),
            S("hat_tinfoil", -0.80, 0, 0.90, 28),
            S("poster_missing_cat", -2.20, 0, 0.40, 88),
            S("jar_unknown_stuff", 0.90, 0, 0.90, 0, dirt=0.7),
        ],
    })

    lots.append({
        "id": "garages_16", "district": "GARAGES", "kind": "GARAGE", "order": 16,
        "min_bid": 600, "info": "DOCS", "pacing": "LEAN",
        "preview": 26, "clearout": 290, "hunters": 8, "lock_chance": 0.25,
        "broom": True,
        "joke": "docs list a first edition; most of the bay is particleboard shelves",
        "tale_ru": "Библиотека в гараже. Дубовый шкаф держит первое издание. ДСП держит пыль. Коньяк «Арарарат» стоит как читательский билет. Метлу просят — книги «дышат».",
        "tale_en": "A library in a garage. The oak shelf holds a first edition. The particleboard holds dust. Ararararat cognac stands in as a library card. They want a broom — the books «breathe».",
        "docs_ru": "ГАРАЖ 16 — БИБЛИОТЕКА:\nШкаф дуб — 1\nПервое издание — 1\nКоньяк — 1\nПишущая машинка «Того Самого»\nМетла — залог",
        "docs_en": "GARAGE 16 — LIBRARY:\nOak bookshelf — 1\nFirst edition — 1\nCognac — 1\nThat Writer's typewriter\nBroom — the deposit",
        "spawns": g_bricks() + g_door_boxes() + [
            S("bookshelf_oak", -2.10, 0, -1.40, 90),
            S("bookshelf_particle", 2.10, 0, -1.40, 90),
            S("sofa_velvet", 0.20, 0, -2.40, -4),
            S("typewriter_writer", 0.15, 0, -1.20, 10),
            S("book_first_edition", -1.50, 0, -0.40, 8),
            S("book_spellbook", -1.50, 0.06, -0.15, -6),
            S("book_encyclopedia", -1.15, 0, -0.40, 70),
            S("book_dictionary", -1.15, 0.06, -0.12, 74),
            S("globe_bar", 1.80, 0, -0.20, -12, nested=["cognac_armenian"]),
            S("lamp_table_banker", -1.70, 0, 0.50, 10),
            S("chair_antique", 1.20, 0, 0.40, -10),
            S("bust_beethoven", 1.90, 0, 0.70, 16),
            S("tool_broom", 2.20, 0, 1.20, 8),
            S("plant_pot_bonsai", -2.15, 0, 1.40, 0),
            S("painting_stern_portrait", -2.20, 0, 0.20, 88),
            S("book_cookbook", 0.40, 0, 0.50, 72),
            S("book_dummies", 0.70, 0, 0.52, 76),
        ],
    })

    lots.append({
        "id": "garages_17", "district": "GARAGES", "kind": "GARAGE", "order": 17,
        "min_bid": 480, "info": "SLIT", "pacing": "JACKPOT",
        "preview": 28, "clearout": 310, "hunters": 8, "lock_chance": 0.28,
        "broom": False,
        "joke": "slit shows moving boxes; Ming vase and gold-coin jar sit at the back",
        "tale_ru": "Щель — коробки. За ними ваза Мин, банка золотых монет и картина неизвестного мастера. Виски 50 лет стоит как охранник. Не два джекпота подряд — этот после пустышки.",
        "tale_en": "The slit is boxes. Behind them: a Ming vase, a jar of gold coins, and an unknown master. The 50-year whiskey stands like security. Not two jackpots in a row — this one follows a bust.",
        "docs_ru": "ГАРАЖ 17 — АНТИК:\nВаза Мин — 1\nБанка золотых монет — 1\nКартина мастера — 1\nВиски 50 лет — 1\nКоробки у ворот — да",
        "docs_en": "GARAGE 17 — ANTIQUE:\nMing vase — 1\nJar of gold coins — 1\nMaster painting — 1\n50-year whiskey — 1\nDoor boxes — yes",
        "spawns": g_bricks() + g_door_boxes() + [
            S("vase_ming", 0.00, 0, -2.40, 10),
            S("coin_jar_gold", -0.70, 0, -2.35, 6),
            S("whiskey_50yo", 0.70, 0, -2.38, 8),
            S("painting_maybe_master", 0.10, 0, -1.50, 4),
            S("dresser_oak", -2.05, 0, -0.70, 90, nested=["ring_wedding", "cash_100"]),
            S("chandelier_crystal", 0.10, 0, -0.50, 12),
            S("statue_bronze", 1.80, 0, -1.20, 10),
            S("teapot_silver", 1.90, 0, -0.40, 14),
            S("rug_persian", 0.10, 0, 0.30, 8),
            S("lamp_table_tiffany", -1.70, 0, 0.50, 10),
            S("safe_hotel", 2.00, 0, 0.90, 8, nested=["cash_100"], locked=1),
            S("plant_pot_bonsai", -2.15, 0, 1.30, 0),
            S("book_first_edition", -1.20, 0, 0.55, 70),
        ],
    })

    lots.append({
        "id": "garages_18", "district": "GARAGES", "kind": "GARAGE", "order": 18,
        "min_bid": 800, "info": "PHOTOS", "pacing": "LEAN",
        "preview": 26, "clearout": 300, "hunters": 8, "lock_chance": 0.22,
        "broom": True,
        "joke": "photos advertise a hamster and a Ming; the bay is an almost-apartment",
        "photos": ["sofa_leather", "vase_ming", "hamster_boris", "plasma_55"],
        "tale_ru": "Почти квартира. Диван, шкаф Нарния, персидский ковёр. На фото — Мин и Борис. Борис в другом районе. Мин тоже. Метлу просят, потому что «почти дом».",
        "tale_en": "Almost an apartment. Sofa, Narnia wardrobe, Persian rug. The photos show a Ming and Boris. Boris is in another district. So is the Ming. They want a broom because it is «almost a home».",
        "docs_ru": "ГАРАЖ 18 — КВАРТИРА:\nДиван кожа — 1\nШкаф Нарния — 1\nКовёр персидский — 1\nВиски односолодовый в ящике\nМин и хомяк — на фото, не здесь",
        "docs_en": "GARAGE 18 — APARTMENT:\nLeather sofa — 1\nNarnia wardrobe — 1\nPersian rug — 1\nSingle malt in a crate\nMing and hamster — in the photos, not here",
        "spawns": g_bricks() + g_door_boxes() + [
            S("sofa_leather", 0.10, 0, -2.40, 4),
            S("fridge_smart", 2.00, 0, -2.15, -6),
            S("wardrobe_narnia", 2.00, 0, -0.30, 90, nested=["hoodie_grey"]),
            S("clock_grandfather_antique", -2.15, 0, -2.15, 4),
            S("dresser_oak", -2.05, 0, -0.50, 90, nested=["cash_20"]),
            S("chandelier_crystal", 0.00, 0, -1.15, 14),
            S("statue_bronze", 1.50, 0, -1.10, 10),
            S("mirror_baroque", 2.20, 0, 0.80, 90),
            S("rug_persian", 0.10, 0, 0.40, 6),
            S("laptop_macbuk", -2.00, 0.92, -0.50, 12),
            S("plate_stack_wedding", 1.60, 0, 0.70, 0),
            S("crate_wine", 0.40, 0, 1.35, -6, nested=["whiskey_single_malt"]),
            S("bicycle_racing", -1.60, 0, 0.50, 90),
            S("plant_pot_bonsai", 2.10, 0, 1.40, 0),
            S("tool_broom", -2.20, 0, 1.50, 8),
            S("vase_soviet_crystal", 1.15, 0, 0.55, 8),
        ],
    })

    # =====================================================================
    # PORT 07–14   continue L J L B J L | L J B L J L B J
    # broom on 09, 10, 12, 13     min_bid 1500–6000     lock ~0.3
    # =====================================================================

    def p_bricks():
        return brick_stack((-0.48, 0.0, 1.48), 3, 2, 4, (0.42, 0.065, 0.36), rot=2)

    def p_smalls():
        # Side alleys (±0.98) in the door brick zone — furniture sits on the centerline.
        return [
            S("cup_soviet_gold", -0.98, 0, 1.55, 0),
            S("cup_okayest", 0.98, 0, 1.55, 8),
            S("cup_okayest", -0.98, 0.12, 1.55, 6),
            S("cup_soviet_gold", 0.98, 0.12, 1.55, -6),
            S("book_dummies", -0.98, 0, 1.90, 72),
            S("book_cookbook", 0.98, 0, 1.90, 70),
            S("perfume_cheap", -0.98, 0, 2.20, 6),
            S("candle_scented", 0.98, 0, 2.20, 0),
            S("letter_aunt", -0.98, 0, 2.48, 4),
            S("bill_coupon", 0.98, 0, 2.48, 0),
            S("cd_mixtape", -0.98, 0, 2.72, 4),
            S("cassette_mixtape", 0.98, 0, 2.72, 8),
        ]

    lots.append({
        "id": "port_07", "district": "PORT", "kind": "PORT", "order": 7,
        "min_bid": 1800, "info": "DOOR15", "pacing": "LEAN",
        "preview": 30, "clearout": 340, "hunters": 8, "lock_chance": 0.28,
        "broom": False,
        "joke": "door-15 furniture run; whiskey in the fridge, bricks at the doors",
        "tale_ru": "Обычный рейс номер два. Диван, шкаф, люстра. Виски в ретро-холодильнике. Кирпичи у дверей — таможня «укрепила» груз. Дед держал тут коллекцию… мебели из каталога.",
        "tale_en": "Ordinary shipment number two. Sofa, wardrobe, chandelier. Whiskey in the retro fridge. Bricks at the doors — customs «reinforced» the cargo. Grandpa kept a collection of… catalog furniture.",
        "docs_ru": "КОНОСАМЕНТ 8802-П\nДиван бархат — 1\nШкаф антик — 1\nЛюстра — 1\nВиски в холодильнике — 1\nКирпичи — «упаковка»",
        "docs_en": "BILL OF LADING 8802-P\nVelvet sofa — 1\nAntique wardrobe — 1\nChandelier — 1\nWhiskey in the fridge — 1\nBricks — «packing»",
        "spawns": p_bricks() + p_smalls() + [
            S("sofa_velvet", 0.00, 0, -2.50, 0),
            S("wardrobe_antique", 0.50, 0, -1.25, 90, nested=["suit_pinstripe"]),
            S("statue_bronze", -0.70, 0, -1.25, 12),
            S("chandelier_crystal", 0.00, 0, -0.05, 8),
            S("fridge_retro", 0.55, 0, 0.95, -6, nested=["whiskey_cheap"]),
            S("bust_marble", -0.70, 0, 0.95, 10),
            S("plate_stack_china", 0.00, 0, 0.95, 0),
            S("typewriter_writer", -0.75, 0, 0.40, 10),
        ],
    })

    lots.append({
        "id": "port_08", "district": "PORT", "kind": "PORT", "order": 8,
        "min_bid": 1600, "info": "TALE", "pacing": "JACKPOT",
        "preview": 36, "clearout": 400, "hunters": 8, "lock_chance": 0.30,
        "broom": False,
        "joke": "legendary: Ming + gold + Rolecks behind a brick curtain at the door",
        "tale_ru": "Контейнер «с историей». История такая: сейф, ваза Мин, слиток, настоящие Ролексы. Аукционист будет говорить про кирпичи. Кирпичи — занавес. Не аплодируйте.",
        "tale_en": "A container «with a history». The history: a safe, a Ming vase, a gold bar, a real Rolecks. The auctioneer will talk about bricks. The bricks are a curtain. Do not clap.",
        "docs_ru": "КОНОСАМЕНТ 8808-ЛЕГЕНДА\nВаза Мин — 1\nСлиток — 1\nРолекс настоящий — 1\nСейф + две пятисотки\nКирпичи у двери — отвлекающий манёвр",
        "docs_en": "BILL OF LADING 8808-LEGEND\nMing vase — 1\nGold bar — 1\nGenuine Rolecks — 1\nSafe + two five-hundreds\nDoor bricks — a decoy",
        "spawns": p_bricks() + p_smalls() + [
            S("safe_old", 0.00, 0, -2.50, 0, nested=["cash_500", "cash_500"], locked=1),
            S("vase_ming", 0.00, 0.72, -2.50, 12),
            S("gold_bar", -0.75, 0, -2.50, 4),
            S("watch_rolecks_real", 0.75, 0, -2.50, 16),
            S("painting_maybe_master", 0.00, 0, -1.70, 4),
            S("whiskey_50yo", -0.70, 0, -1.70, 8),
            S("coin_jar_gold", 0.70, 0, -1.70, 6),
            S("usb_crypto", -0.70, 0, -1.05, 0),
            S("ring_diamond", 0.70, 0, -1.05, 40),
            S("chandelier_grand", 0.00, 0, -0.45, 8),
            S("wardrobe_antique", 0.50, 0, 0.75, 90, nested=["fur_coat"]),
        ],
    })

    lots.append({
        "id": "port_09", "district": "PORT", "kind": "PORT", "order": 9,
        "min_bid": 5500, "info": "DOCS", "pacing": "BUST",
        "preview": 26, "clearout": 310, "hunters": 8, "lock_chance": 0.22,
        "broom": True,
        "joke": "manifest lists a helicopter; the box is bricks, a mouse, and a left sneaker",
        "tale_ru": "Коносамент обещает вертолёт. Вертолёта нет. Есть кирпичи, мышь и левый кроссовок. Таможня поставила печать «стройматериалы» дважды — на всякий случай. Метлу просят, мышь не мести.",
        "tale_en": "The manifest promises a helicopter. No helicopter. There are bricks, a mouse, and a left sneaker. Customs stamped «building materials» twice — just in case. They want a broom. Do not sweep the mouse.",
        "docs_ru": "КОНОСАМЕНТ 9909-П\n1× Вертолёт — НЕТ\n1× Автомобиль — НЕТ\n1× Кроссовок левый — да\nКирпичи — да\nМышь — не в описи, в контейнере",
        "docs_en": "BILL OF LADING 9909-P\n1× Helicopter — NO\n1× Automobile — NO\n1× Left sneaker — yes\nBricks — yes\nMouse — not on the sheet, in the box",
        "spawns": brick_stack((-0.50, 0.0, -2.40), 3, 3, 5, (0.44, 0.065, 0.72), rot=2) + [
            S("shoe_sneaker_single", 0.15, 0, 2.50, 32, dirt=0.6),
            S("mouse_live", -0.80, 0, 2.45, 8),
            S("gold_bar_painted", 0.80, 0, 2.40, 4, dirt=0.5),
            S("hat_tinfoil", -0.20, 0, 2.10, 30),
            S("rag_dirty", 0.70, 0, 2.05, 16, dirt=0.85),
            S("tool_broom", 0.80, 0, 1.70, 90),
            S("plant_pot_dead", -1.00, 0, 1.70, 0, dirt=0.8),
            S("sock_single", 0.00, 0, 1.85, 10, dirt=0.7),
        ],
    })

    lots.append({
        "id": "port_10", "district": "PORT", "kind": "PORT", "order": 10,
        "min_bid": 2200, "info": "SLIT", "pacing": "LEAN",
        "preview": 32, "clearout": 360, "hunters": 8, "lock_chance": 0.30,
        "broom": True,
        "joke": "slit shows an engine block; oil and gasoline share the aisle",
        "tale_ru": "Контейнер СТО. Щель — блок двигателя. Масло и бензин едут вместе, как плохая идея. Инструментов почти нет — редко. Метлу просят из суеверия.",
        "tale_en": "A shop container. The slit is an engine block. Oil and gasoline travel together, like a bad idea. Almost no tools — rare. They want a broom out of superstition.",
        "docs_ru": "КОНОСАМЕНТ 1010-СТО\nБлок двигателя — 1\nМасло бочка + канистра\nПокрышки — 2\nМетла — залог\nV8 хром — нет, в другом гараже",
        "docs_en": "BILL OF LADING 1010-SHOP\nEngine block — 1\nOil barrel + canister\nTires — 2\nBroom — deposit\nChrome V8 — no, another garage",
        "spawns": p_bricks() + p_smalls() + [
            S("engine_block", 0.00, 0, -2.45, 10, dirt=0.4),
            S("oil_barrel", -0.70, 0, -1.60, 6),
            S("gasoline_canister", 0.70, 0, -1.60, 10),
            S("oil_jug_engine", -0.70, 0, -0.90, 14),
            S("toolbox_red", 0.70, 0, -0.90, -8, nested=["wrench_adjustable"]),
            S("tire_bald", -0.70, 0, -0.15, 8),
            S("tire_racing", 0.70, 0, -0.15, -6),
            S("fan_industrial", 0.00, 0, 0.55, 8),
            S("wrench_giant", -0.85, 0, 0.85, 36),
            S("tool_broom", 0.90, 0, 0.85, 8),
            S("rag_dirty", 0.00, 0, 0.90, 16, dirt=0.5),
        ],
    })

    lots.append({
        "id": "port_11", "district": "PORT", "kind": "PORT", "order": 11,
        "min_bid": 1700, "info": "PHOTOS", "pacing": "JACKPOT",
        "preview": 38, "clearout": 410, "hunters": 8, "lock_chance": 0.32,
        "broom": False,
        "joke": "photos show a cracked TV and boxes; plasma + master + crypto sit in the back",
        "photos": ["tv_plasma_cracked", "box_moving", "vase_ming_fake", "hamster_boris"],
        "tale_ru": "Фото врёт треснутым теликом. Внутри — плазма 55, картина мастера и флешка-кошелёк. Виски 50 лет. Кирпичи у двери, чтобы хантеры зевали.",
        "tale_en": "The photos lie with a cracked TV. Inside: a 55-inch plasma, a master painting, and a wallet stick. 50-year whiskey. Bricks at the door so the hunters yawn.",
        "docs_ru": "КОНОСАМЕНТ 1111-МЕДИА\nПлазма 55 — 1\nКартина мастера — 1\nФлешка крипто — 1\nВиски 50 лет — 1\nХомяк на фото — нет",
        "docs_en": "BILL OF LADING 1111-MEDIA\n55-inch plasma — 1\nMaster painting — 1\nCrypto USB — 1\n50-year whiskey — 1\nHamster in the photos — no",
        "spawns": p_bricks() + p_smalls() + [
            S("plasma_55", 0.00, 0, -2.50, 4),
            S("painting_maybe_master", 0.00, 0, -1.70, 4),
            S("usb_crypto", -0.75, 0, -1.70, 0),
            S("whiskey_50yo", 0.75, 0, -1.70, 8),
            S("ring_diamond", 0.00, 0, -1.05, 36),
            S("safe_hotel", -0.70, 0, -1.05, 8, nested=["cash_100"], locked=1),
            S("chandelier_crystal", 0.00, 0, -0.40, 8),
            S("wardrobe_antique", 0.50, 0, 0.75, 90, nested=["suit_pinstripe"]),
            S("camera_dslr", -0.75, 0, 0.85, -14),
        ],
    })

    lots.append({
        "id": "port_12", "district": "PORT", "kind": "PORT", "order": 12,
        "min_bid": 2500, "info": "DOOR15", "pacing": "LEAN",
        "preview": 32, "clearout": 370, "hunters": 8, "lock_chance": 0.30,
        "broom": True,
        "joke": "door-15 antiques plus champagne; broom tax because the rug «sheds»",
        "tale_ru": "Антиквариат вторым классом. Шкаф, часы напольные, шампанское полусладкое. Ковёр «персидский» линяет — поэтому метла. Дед держал тут коллекцию… этикеток.",
        "tale_en": "Antiques, second class. Wardrobe, tall clock, semi-sweet champagne. The Persian-ish rug sheds — hence the broom. Grandpa kept a collection of… labels.",
        "docs_ru": "КОНОСАМЕНТ 1212-АНТИК\nШкаф антик — 1\nЧасы напольные антик — 1\nШампанское — 1\nКовёр — линяет\nМетла — залог",
        "docs_en": "BILL OF LADING 1212-ANTIQUE\nAntique wardrobe — 1\nAntique grandfather clock — 1\nChampagne — 1\nRug — sheds\nBroom — deposit",
        "spawns": p_bricks() + p_smalls() + [
            S("sofa_velvet", 0.00, 0, -2.50, 0),
            S("wardrobe_antique", 0.50, 0, -1.25, 90, nested=["hat_top"]),
            S("clock_grandfather_antique", -0.70, 0, -1.25, 4),
            S("chandelier_crystal", 0.00, 0, -0.05, 8),
            S("rug_doormat", 0.00, 0, 0.55, 6),
            S("crate_wine", 0.55, 0, 0.95, -6, nested=["champagne_fake"]),
            S("bust_beethoven", -0.70, 0, 0.95, 12),
            S("teapot_silver", -0.75, 0, 0.40, 8),
            S("tool_broom", 0.80, 0, 0.40, 90),
            S("painting_black_square", 0.00, 0, -1.80, 4),
        ],
    })

    lots.append({
        "id": "port_13", "district": "PORT", "kind": "PORT", "order": 13,
        "min_bid": 5800, "info": "TALE", "pacing": "BUST",
        "preview": 25, "clearout": 300, "hunters": 8, "lock_chance": 0.20,
        "broom": True,
        "joke": "customs seizure: paint, mice, painted bars, one sad mannequin",
        "tale_ru": "Конфискат. Хозяин обещал «коллекцию императора». Император носил шапочку из фольги. Мыши оформили акт. Краска золотая ещё мокрая. Метлу просят — и правильно.",
        "tale_en": "A seizure. Owner promised «an emperor's collection». The emperor wore tinfoil. The mice filed the report. The gold paint is still wet. They want a broom — correctly.",
        "docs_ru": "АКТ ИЗЪЯТИЯ 1313\nКоллекция императора — НЕТ\nСлитки — краска\nМыши — 2\nМанекен без головы — 1\nКраска золото — 1 (мокрая)",
        "docs_en": "SEIZURE ACT 1313\nEmperor's collection — NO\nGold bars — paint\nMice — 2\nHeadless mannequin — 1\nGold paint — 1 (wet)",
        "spawns": brick_stack((-0.50, 0.0, -2.35), 3, 2, 5, (0.44, 0.065, 0.70), rot=3) + [
            S("mannequin_headless", 0.00, 0, 2.45, 180, dirt=0.5),
            S("mouse_live", -0.85, 0, 2.40, 8),
            S("mouse_white", 0.85, 0, 2.38, -10),
            S("gold_bar_painted", -0.40, 0, 1.85, 4, dirt=0.6),
            S("gold_bar_painted", 0.10, 0, 1.88, -6, dirt=0.6),
            S("gold_bar_painted", 0.55, 0, 1.82, 10, dirt=0.6),
            S("paint_gold", -0.90, 0, 1.70, 0, dirt=0.4),
            S("hat_tinfoil", 0.90, 0, 1.65, 28),
            S("rag_dirty", -0.20, 0, 1.55, 16, dirt=0.9),
            S("tool_broom", 0.80, 0, 1.15, 90),
            S("plant_pot_dead", -1.00, 0, 1.20, 0, dirt=0.85),
            S("vase_ming_fake", 0.00, 0, 1.15, 8, dirt=0.5),
            S("sock_single", 0.40, 0, 1.20, 12, dirt=0.8),
            S("watch_rolecks_fake", -0.40, 0, 1.18, 20),
            S("poster_missing_cat", 0.00, 0, 0.70, 4),
        ],
    })

    lots.append({
        "id": "port_14", "district": "PORT", "kind": "PORT", "order": 14,
        "min_bid": 1900, "info": "DOCS", "pacing": "JACKPOT",
        "preview": 40, "clearout": 420, "hunters": 8, "lock_chance": 0.32,
        "broom": False,
        "joke": "finale: Ming, gold, Rolecks, Boris — docs pretend it's chairs",
        "tale_ru": "Последний контейнер волны. Дед держал тут коллекцию… всего. Ваза Мин, слиток, Ролексы, Борис. Коносамент пишет «стулья». Стульев нет. Не зевайте.",
        "tale_en": "Last container of the wave. Grandpa kept a collection of… everything. Ming vase, gold bar, Rolecks, Boris. The bill of lading says «chairs». No chairs. Do not yawn.",
        "docs_ru": "КОНОСАМЕНТ 1414-ФИНАЛ\nСтулья — НЕТ\nВаза Мин — 1\nСлиток — 1\nРолекс настоящий — 1\nХомяк Борис — 1\nСейф + две пятисотки\nПечать: «не трясти». Трясли.",
        "docs_en": "BILL OF LADING 1414-FINALE\nChairs — NO\nMing vase — 1\nGold bar — 1\nGenuine Rolecks — 1\nBoris the hamster — 1\nSafe + two five-hundreds\nStamp: «do not shake». They shook it.",
        "spawns": p_bricks() + p_smalls() + [
            S("safe_old", 0.00, 0, -2.50, 0, nested=["cash_500", "cash_500"], locked=1),
            S("vase_ming", 0.00, 0.72, -2.50, 10),
            S("gold_bar", -0.75, 0, -2.50, 4),
            S("watch_rolecks_real", 0.75, 0, -2.50, 16),
            S("hamster_boris", -0.70, 0, -1.70, 18),
            S("whiskey_50yo", 0.70, 0, -1.70, 8),
            S("painting_maybe_master", 0.00, 0, -1.70, 4),
            S("ring_diamond", 0.00, 0, -1.05, 36),
            S("necklace_pearl", -0.70, 0, -1.05, 22),
            S("coin_jar_gold", 0.70, 0, -1.05, 6),
            S("chandelier_grand", 0.00, 0, -0.45, 8),
            S("wardrobe_antique", 0.50, 0, 0.75, 90, nested=["fur_coat", "hat_top"]),
        ],
    })

    return lots


# Empty TALE / DOCS on the frozen wave-1 presets (ids/order/spawns unchanged).
PREVIEW_FILL = {
    "hangar_01": {
        "tale_ru": "Дед держал тут коллекцию… чего-то леопардового. На фото — Ролеккс. В сумке — раскладушка и двадцатка. Аукционист моргает первым.",
        "tale_en": "Grandpa kept a collection of… something leopard. The photos show a Rolecks. The bag has a flip phone and a twenty. The auctioneer blinks first.",
        "docs_ru": "ОПИСЬ (сдал администратор качалки):\n— сумка леопард\n— шкатулка детская\n— часы Ролеккс (на фото, не в сумке)\n— термос, свеча, рамка с котом",
        "docs_en": "MANIFEST (gym front-desk intake):\n— leopard bag\n— kids jewelry box\n— Rolecks (in the photo, not in the bag)\n— thermos, candle, framed cat",
    },
    "hangar_02": {
        "docs_ru": "ОПИСЬ (таможня, три границы):\n— чемодан пластик\n— носок — 1 (второй в розыске)\n— шапочка из фольги\n— билет лотереи, постер «Успех!»",
        "docs_en": "MANIFEST (customs, three borders):\n— plastic suitcase\n— sock — 1 (the other is wanted)\n— tinfoil hat\n— lottery ticket, SUCCESS! poster",
    },
    "hangar_03": {
        "tale_ru": "Рабочая сумка. Хозяин клялся, что там только бутерброды. В бархатной шкатулке — дедовы карманные часы. На фото — Мин и слиток. Мин в отпуске.",
        "tale_en": "A work bag. Owner swore it was only sandwiches. The velvet box holds grandpa's pocket watch. Photos show a Ming and a gold bar. The Ming is on vacation.",
        "docs_ru": "ОПИСЬ (сдал отдел кадров):\n— сумка рабочая\n— шкатулка + часы карманные\n— Polaroyd\n— ваза Мин / слиток — на фото, не здесь",
        "docs_en": "MANIFEST (HR intake):\n— work bag\n— jewelry box + pocket watch\n— Polaroyd\n— Ming / gold bar — in the photos, not here",
    },
    "hangar_04": {
        "tale_ru": "Школьный рюкзак. Аукционист говорит, что внутри МакБук. МакБук в описи. В рюкзаке — флешка с котами и пятёрка. Том 7 энциклопедии не врёт: он тяжёлый.",
        "tale_en": "A school backpack. Auctioneer says there's a MacBuk inside. The MacBuk is on the sheet. The pack has a cat-video stick and a five. Encyclopedia vol. 7 does not lie: it is heavy.",
    },
    "hangar_05": {
        "tale_ru": "Турист не прилетел. Чемоданчик детский, Polaroyd, тарелка из Сочи. На фото — МакБук, который не зарегистрировали на рейс.",
        "tale_en": "The tourist missed the flight. Kids suitcase, Polaroyd, a Sochi plate. The photos show a MacBuk that never checked in.",
        "docs_ru": "ОПИСЬ (камера хранения, аэропорт):\n— чемодан детский + Барбее\n— Polaroyd\n— авоська с иностранной купюрой\n— МакБук — в фото, не в рейсе",
        "docs_en": "MANIFEST (airport left luggage):\n— kids suitcase + Barbee\n— Polaroyd\n— tote with a foreign note\n— MacBuk — in the photo, not on the flight",
    },
    "hangar_06": {
        "docs_ru": "ОПИСЬ (патентное бюро, салфетка):\n— сумка спорт\n— Нокла 3310\n— радиола ВЭФ\n— ноут 2005\n— патент на скрепку — к описи не прилагается",
        "docs_en": "MANIFEST (patent office, napkin):\n— gym bag\n— Nokla 3310\n— VEF radio\n— 2005 laptop\n— paperclip patent — not attached",
    },
    "hangar_07": {
        "tale_ru": "Инспектор был пьян и честен по частям. Ваза Мин в описи. Носок в коробке. Это единственная правда, которую он унёс с собой.",
        "tale_en": "The inspector was drunk and honest in parts. Ming vase on the sheet. A sock in the box. That is the only truth he took with him.",
    },
    "hangar_08": {
        "tale_ru": "Походный рюкзак. На фото — сейф и карта сокровищ. В рюкзаке — фонарь и двадцатка. Сокровище — письмо, которое указывает на чужой гараж.",
        "tale_en": "A hiking pack. Photos show a safe and a treasure map. The pack has a flashlight and a twenty. The treasure is a letter that points at someone else's garage.",
        "docs_ru": "ОПИСЬ (турклуб «Горизонт»):\n— рюкзак туристический\n— фонарь, канистра воды\n— карта сокровищ\n— сейф на фото — нет",
        "docs_en": "MANIFEST (Horizon hiking club):\n— hiking backpack\n— flashlight, water can\n— treasure map\n— safe in the photo — no",
    },
    "storage_01": {
        "tale_ru": "Ячейка «ИКЕЙЯ». Каждый шкаф шатается в свою сторону. Аукционист называет это «динамической композицией». Смотритель называет это «залог».",
        "tale_en": "An IKEYA unit. Every cabinet leans a different way. The auctioneer calls it a «dynamic composition». The caretaker calls it a «deposit».",
        "docs_ru": "ЯЧЕЙКА 01 — ЖИЛЬЁ:\nКомод ИКЕЙЯ — 1 (шатается)\nХолодильник мини — 1\nТелек «Рубин» — 1\nКоробки у двери — хрупкое, честно",
        "docs_en": "UNIT 01 — LIVING:\nIKEYA dresser — 1 (wobbles)\nMini fridge — 1\nRoobin CRT — 1\nDoor boxes — fragile, honestly",
    },
    "storage_02": {
        "tale_ru": "Тёмная бабушкина. Лампочки нет — фонарик берите сами. В комоде жемчуг пластиковый и двадцатка. Виски в ящике — «на гостей», гостей нет.",
        "tale_en": "Dark grandma unit. No bulb — bring your own light. The dresser holds plastic pearls and a twenty. Whiskey in the crate is «for guests». There are no guests.",
        "docs_ru": "ЯЧЕЙКА 02 — БАБУШКА (темно):\nМатрас в пятнах — 1\nКомод + чемодан сверху\nВиски / водка в ящике\nСвет не включать: лампочки нет",
        "docs_en": "UNIT 02 — GRANDMA (dark):\nStained mattress — 1\nDresser + suitcase on top\nWhiskey / vodka in a crate\nDo not turn on the light: there is no bulb",
    },
    "storage_03": {
        "tale_ru": "Стена из коробок у двери. За ней — Борис. Аукционист будет говорить про «обычный хлам». Борис видел вещи. Борис молчит.",
        "tale_en": "A wall of boxes at the door. Behind it — Boris. The auctioneer will say «ordinary junk». Boris has seen things. Boris says nothing.",
        "docs_ru": "ЯЧЕЙКА 03 — КОРОБКИ:\nСтена у двери — да\nХомяк Борис — 1 (сзади)\nЧемодан кожа + сотка\nФлешка крипто в сигарной коробке",
        "docs_en": "UNIT 03 — BOXES:\nDoor wall — yes\nBoris the hamster — 1 (in back)\nLeather suitcase + a hundred\nCrypto stick in a cigar box",
    },
    "storage_05": {
        "docs_ru": "ЯЧЕЙКА 05 — ФОКУС:\nГолубь — нет\nЯчейка распилена — кем-то другим\nМатрас + пустые коробки\nКирпич «золото» — 1\nМетла — иначе залог",
        "docs_en": "UNIT 05 — MAGIC:\nDove — no\nUnit sawed — by someone else\nMattress + empty boxes\n«Gold» brick — 1\nBroom — or they keep the deposit",
    },
    "storage_04": {
        "tale_ru": "Локер охранника ночной смены. Он думал, бумбокс золотой — это краска. Зеркалка «Кэнун» под худи. Катана не влезла и ушла гулять.",
        "tale_en": "Night-shift guard's locker. He thought the gold boombox was paint. A Canun DSLR under a hoodie. The katana didn't fit and went for a walk.",
    },
    "storage_06": {
        "tale_ru": "Сорок чашек. Хозяин коллекционировал «золотой ободок». Сорок раз. Аукционист называет это сервизом. Скупщик назовёт это проблемой.",
        "tale_en": "Forty teacups. The owner collected «gold rims». Forty times. The auctioneer calls it a service set. The vendor will call it a problem.",
        "docs_ru": "ЛОКЕР 06 — ФАРФОР:\nЧашка с золотом × 40\nДругого нет\nВес: не взвешивали\nПримечание: не ронять. Все.",
        "docs_en": "LOCKER 06 — CHINA:\nGold-trim teacup × 40\nNothing else\nWeight: not weighed\nNote: do not drop. Any of them.",
    },
    "storage_07": {
        "tale_ru": "Картина к стене. Может, мастер. Может, мотель. На фото — плазма и слиток. В ячейке — лампа Тиффани и кольцо выпускника. Метла у двери, залог любят.",
        "tale_en": "A painting face to the wall. Maybe a master. Maybe a motel. Photos show a plasma and a gold bar. The unit has a Tiffanny lamp and a class ring. Broom at the door — they love the deposit.",
        "docs_ru": "ЯЧЕЙКА 07 — ЖИВОПИСЬ:\nКартина «мастер?» — к стене\nЛампа Тиффани — 1\nПлазма / слиток — на фото\nМетла — обязательна",
        "docs_en": "UNIT 07 — PAINTING:\n«Master?» painting — face to wall\nTiffanny lamp — 1\nPlasma / gold — in the photos\nBroom — required",
    },
    "storage_08": {
        "tale_ru": "Мастерская. Бензин, масло, краска «золото». Ящик деда с пятидесяткой. Аукционист скажет «обычный гараж». Обычный гараж не стоит вашего весла вслепую.",
        "tale_en": "A workshop. Gasoline, oil, gold paint. Grandpa's toolbox with a fifty. The auctioneer will say «ordinary garage». An ordinary garage is not worth a blind paddle.",
        "docs_ru": "ЯЧЕЙКА 08 — СТО:\nПолка + два ящика\nМотор газонокосилки\nБензин / масло / краски\nЯщик «взрывоопасно» — заперт",
        "docs_en": "UNIT 08 — SHOP:\nShelf + two toolboxes\nLawnmower engine\nGas / oil / paints\nEXPLOSIVE crate — locked",
    },
    "storage_09": {
        "tale_ru": "Бабушкин сервант. Самовар, шуба, письмо Деду Морозу от сорокатрёхлетнего. Глобус-бар не врёт: внутри стопки.",
        "tale_en": "Grandma's sideboard. Samovar, fur coat, a letter to Santa from a forty-three-year-old. The globe bar does not lie: there are shot glasses inside.",
        "docs_ru": "ЯЧЕЙКА 09 — БАБУШКА:\nКомод + чемодан кожа\nСамовар + чайник серебро\nШуба\nПисьмо Деду Морозу — 1",
        "docs_en": "UNIT 09 — GRANDMA:\nDresser + leather suitcase\nSamovar + silver teapot\nFur coat\nLetter to Santa — 1",
    },
    "storage_10": {
        "tale_ru": "Антиквариат, говорит печать. Печать кривая. Ваза Мин из Мининска, слитки из ларька, сейф уже вскрыт. Свет портит патину, которой нет.",
        "tale_en": "Antiques, says the stamp. The stamp is crooked. A Ming from Minsk, kiosk gold bars, a safe already cracked. Light ruins a patina that is not there.",
    },
    "storage_11": {
        "tale_ru": "Дубовый комод скучный с двери. В заднем ящике — кольцо с бриллиантом. Или очень уверенное стекло. Аукционист зевает специально.",
        "tale_en": "An oak dresser that looks boring from the door. The back drawer holds a diamond ring. Or very confident glass. The auctioneer yawns on purpose.",
        "docs_ru": "ЯЧЕЙКА 11 — МЕБЕЛЬ:\nКомод дуб + кольца\nШкатулка музыкальная\nКнижный шкаф дуб\nКоробки у двери — отвлекают",
        "docs_en": "UNIT 11 — FURNITURE:\nOak dresser + rings\nMusic box\nOak bookshelf\nDoor boxes — a decoy",
    },
    "storage_12": {
        "tale_ru": "Репетиция в ячейке. Две гитары, синтезатор, золотой диск. Соседи жаловались на «Собачий вальс». Пианино убитое — в другом гараже.",
        "tale_en": "A rehearsal unit. Two guitars, a synth, a gold record. Neighbors complained about Chopsticks. The ruined piano is in another garage.",
        "docs_ru": "ЯЧЕЙКА 12 — РЕПЕТИЦИЯ:\nГитара акустика + розовая электро\nСинтезатор 80-х\nЗолотой диск\nДиско-шар — да, он",
        "docs_en": "UNIT 12 — REHEARSAL:\nAcoustic + pink electric\n'80s synth\nGold record\nDisco ball — yes, that",
    },
    "garages_01": {
        "tale_ru": "Хлам у ворот. Диван и фарфор — у задней стены. Классика района: хантеры ставят на то, что видят в щель.",
        "tale_en": "Junk at the door. The sofa and the china are at the back wall. A district classic: hunters bid on what the slit shows.",
        "docs_ru": "ГАРАЖ 01 — ПЕРЕЕЗД:\nДиван кожа — 1\nФарфор — 1\nВелик гоночный — 1\nКоробки у ворот — да",
        "docs_en": "GARAGE 01 — MOVE:\nLeather sofa — 1\nChina — 1\nRacing bike — 1\nDoor boxes — yes",
    },
    "garages_02": {
        "tale_ru": "Гаражный парламент. Фанерный трон смотрит на бронзовую статую. Пианино «Красный Октябрь» ведёт протокол. Собаки на картине играют в покер без кворума.",
        "tale_en": "Garage parliament. A plywood throne faces a bronze statue. The Red October upright keeps minutes. The dogs in the painting play poker without a quorum.",
        "docs_ru": "ГАРАЖ 02 — ПАРЛАМЕНТ:\nПианино + диван бархат\nТрон фанерный — 1\nСтатуя бронза — 1\nЯщик винный — да",
        "docs_en": "GARAGE 02 — PARLIAMENT:\nUpright + velvet sofa\nPlywood throne — 1\nBronze statue — 1\nWine crate — yes",
    },
    "garages_03": {
        "tale_ru": "Щель показывает коробки. Рояль и виски 50 лет стоят у задней стены и не представляются. Сейф гостиничный заперт — как все гостиничные сейфы в этой игре.",
        "tale_en": "The slit shows boxes. The grand piano and the 50-year whiskey stand at the back wall and do not introduce themselves. The hotel safe is locked — like every hotel safe in this game.",
        "docs_ru": "ГАРАЖ 03 — КОНЦЕРТ:\nРояль — 1\nВиски 50 лет — 1\nЛюстра дворцовая — 1\nКоробки у ворот — отвлекают",
        "docs_en": "GARAGE 03 — CONCERT:\nGrand piano — 1\n50-year whiskey — 1\nPalace chandelier — 1\nDoor boxes — a decoy",
    },
    "garages_04": {
        "tale_ru": "Мастерская с Нарнией. Задней стенки нет — дальше стена. Мотор V8 хромированный настоящий. Вертолёт дописали карандашом и сами посмеялись.",
        "tale_en": "A workshop with Narnia. No back panel — just the wall. The chrome V8 is real. Someone added a helicopter in pencil and laughed at themselves.",
    },
    "garages_05": {
        "docs_ru": "ГАРАЖ 05 — ФОРТ НОКС:\nСлитки — краска из ларька\nДиван — четыре семьи\nХолодильник — рыба 2009\nМетлу не оставляйте",
        "docs_en": "GARAGE 05 — FORT KNOX:\nGold bars — kiosk paint\nSofa — four families\nFridge — a fish from 2009\nDo not leave a broom",
    },
    "garages_06": {
        "tale_ru": "Семейный гараж. Шкаф антик, диван бархат, самовар нет — он в ячейке. Детский велик лежит как обвинение. Письма в сундуке бабушки не ваши.",
        "tale_en": "A family garage. Antique wardrobe, velvet sofa, no samovar — that's in a storage unit. A kids' bike lies there like an accusation. The letters in grandma's chest are not yours.",
        "docs_ru": "ГАРАЖ 06 — СЕМЬЯ:\nШкаф антик — 1\nДиван бархат — 1\nЛюстра хрусталь — 1\nСундук бабушкин — письма",
        "docs_en": "GARAGE 06 — FAMILY:\nAntique wardrobe — 1\nVelvet sofa — 1\nCrystal chandelier — 1\nGrandma's chest — letters",
    },
    "garages_07": {
        "tale_ru": "Кирпичи у ворот. Единственное, что не кирпич — гитара с автографом и Ролексы в ящике. Аукционист зевает. Зевьте в ответ и берите весло.",
        "tale_en": "Bricks at the door. The only thing that is not a brick is a signed guitar and a Rolecks in the toolbox. The auctioneer yawns. Yawn back and raise the paddle.",
        "docs_ru": "ГАРАЖ 07 — КИРПИЧИ:\nКирпич × много\nГитара с автографом — 1\nЯщик деда + Ролекс + 500\nСейф — заперт",
        "docs_en": "GARAGE 07 — BRICKS:\nBrick × many\nSigned guitar — 1\nGrandpa's box + Rolecks + 500\nSafe — locked",
    },
    "garages_08": {
        "tale_ru": "Почти дом. Диван, умный холодильник, Нарния, напольные часы. Пианино убитое играет «Собачий вальс» само. Вывозите вчетвером.",
        "tale_en": "Almost a house. Sofa, smart fridge, Narnia, a tall clock. The ruined piano plays Chopsticks by itself. Clear it out as a team of four.",
        "docs_ru": "ГАРАЖ 08 — ДОМ:\nДиван кожа — 1\nХолодильник умный — 1\nЧасы напольные антик — 1\nПианино убитое — само играет",
        "docs_en": "GARAGE 08 — HOME:\nLeather sofa — 1\nSmart fridge — 1\nAntique grandfather clock — 1\nRuined piano — plays itself",
    },
    "port_01": {
        "tale_ru": "Обычный рейс. На фото — Мин и Борис. В контейнере — диван, шкаф, зуб Элвиса в банке. Борис в другом лоте. Мин тоже.",
        "tale_en": "An ordinary shipment. Photos show a Ming and Boris. The container has a sofa, a wardrobe, and Elvis's tooth in a jar. Boris is in another lot. So is the Ming.",
        "docs_ru": "КОНОСАМЕНТ 0101\nДиван бархат — 1\nШкаф антик — 1\nЗуб Элвиса — 1\nМин / Борис — на фото",
        "docs_en": "BILL OF LADING 0101\nVelvet sofa — 1\nAntique wardrobe — 1\nElvis's tooth — 1\nMing / Boris — in the photos",
    },
    "port_02": {
        "tale_ru": "Легенда доков. Сейф с двумя пятисотками, настоящая Мин, слиток, Ролексы. На фото — фальшивая ваза и Борис. Хантеры смотрят фото.",
        "tale_en": "The dock legend. A safe with two five-hundreds, a real Ming, a gold bar, a Rolecks. Photos show a fake vase and Boris. The hunters look at the photos.",
        "docs_ru": "КОНОСАМЕНТ 0202-ЛЕГЕНДА\nСейф + 1000 наличными\nВаза Мин — 1\nСлиток + Ролекс\nФото врёт",
        "docs_en": "BILL OF LADING 0202-LEGEND\nSafe + $1000 cash\nMing vase — 1\nGold bar + Rolecks\nPhotos lie",
    },
    "port_03": {
        "tale_ru": "Коносамент 7741. Вертолёт и Волга — нет. Рояль — нет, есть шкаф. Люстра — да. Печать «не трясти» пережила всю дорогу в виде тряски.",
        "tale_en": "Bill of lading 7741. Helicopter and Volga — no. Grand piano — no, there's a wardrobe. Chandelier — yes. The «do not shake» stamp survived the whole trip as shaking.",
    },
    "port_04": {
        "docs_ru": "КОНОСАМЕНТ 0404-ДУБАЙ\nШлёпанец султана — 1 (кроссовок)\nКирпичи — остальные\nПечать: стройматериалы\nТаможня смеялась",
        "docs_en": "BILL OF LADING 0404-DUBAI\nSultan's flip-flop — 1 (a sneaker)\nBricks — the rest\nStamp: building materials\nCustoms laughed",
    },
    "port_05": {
        "tale_ru": "Клоун у двери. Манекен в костюме стоит в проёме, чтобы победитель охнул. За ним — Мин, слиток, сейф. Не убегайте сразу.",
        "tale_en": "Clown at the door. A costumed mannequin stands in the opening so the winner yelps. Behind it: a Ming, gold bars, a safe. Do not run immediately.",
        "docs_ru": "КОНОСАМЕНТ 0505-ЦИРК\nМанекен + костюм клоуна — у двери\nВаза Мин + слитки + сейф — сзади\nВиски 50 лет — 1\nНе пугаться. Потом пугаться.",
        "docs_en": "BILL OF LADING 0505-CIRCUS\nMannequin + clown suit — at the door\nMing + gold + safe — in back\n50-year whiskey — 1\nDo not panic. Then panic.",
    },
    "port_06": {
        "tale_ru": "Последний контейнер первой волны. Два слитка на диване, шкаф, рояль нет — пианино. На фото снова Мин и Борис. Они уже стали мемом района.",
        "tale_en": "Last container of wave one. Two gold bars on the sofa, a wardrobe, no grand — an upright. Photos again show a Ming and Boris. They are already a district meme.",
        "docs_ru": "КОНОСАМЕНТ 0606\nДиван + два слитка сверху\nШкаф антик — 1\nПианино — 1\nМин / Борис — на фото",
        "docs_en": "BILL OF LADING 0606\nSofa + two gold bars on top\nAntique wardrobe — 1\nUpright piano — 1\nMing / Boris — in the photos",
    },
}
